name: CI-CD Full Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Give execute permission
        run: chmod +x app/check_app.sh

      - name: Run application check script
        run: ./app/check_app.sh

      - name: Display index.html content
        run: cat app/index.html

      - name: Display secrets and environment variables
        env:
          CUSTOM_ENV: "HelloFromCI"
          RUNNER_OS: ${{ runner.os }}
          FAKE_API_TOKEN: ${{ secrets.FAKE_API_TOKEN }}
          ENV_TYPE: ${{ secrets.ENV_TYPE }}
        run: |
          echo "Custom env: $CUSTOM_ENV"
          echo "Runner OS: $RUNNER_OS"
          echo "Fake API Token (masked): $FAKE_API_TOKEN"
          echo "Environment type (masked): $ENV_TYPE"

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install ansible -y

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
      
      - name: Create Ansible inventory file
        run: |
          mkdir -p ansible
          cat > ansible/inventory.ini << EOF
          [web]
          ${{ secrets.SERVER_IP }} ansible_user=${{ secrets.SERVER_USER }} ansible_ssh_common_args='-o StrictHostKeyChecking=no'
          EOF
          chmod 600 ansible/inventory.ini

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml \
            --private-key ~/.ssh/deploy_key

      - name: Verify deployment
        run: |
          echo "Checking Nginx status..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "systemctl is-active nginx"
          echo "Testing web response..."
          if [ "$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.SERVER_IP }})" != "200" ]; then
            echo "Web check failed!"
            exit 1
          fi